### ISSUE TITLE
How to support more detailed scan?

### ISSUE THREAD

**Issue by xhzengAIB** [AlexDenisov/ToyClangPlugin#1]
Hi! @AlexDenisov 

How to prevent beginners low-level mistakes, such as variable A, B, etc., the delegate is not released, block, A circular reference.

Jack

**Comment by AlexDenisov** [comment]
Oh, @xhzengAIB, please, take my apologies, I've missed this issue :disappointed: 
To be honest I don't have too much knowledge in this area. 
Regarding variable names: probably you can just check length of a variable, maybe with some exceptions, e.g. do not check 'index' variables in loops (`i`, `j`, `k`). Or apply some more 'sophisticated' technics like `spell checking`, e.g. break variable name into list of words (`leftLabel` -> `[left, label]`) and check (like actually AppCode does).
Regarding delegates, blocks, etc.: I'd recommend to take a look at [Clang Static Analyzer](http://clang-analyzer.llvm.org) and this video/slides: Building a Checker in 24 hours ([Slides](http://llvm.org/devmtg/2012-11/Zaks-Rose-Checker24Hours.pdf)  , [Video](http://llvm.org/devmtg/2012-11/videos/Zaks-Rose-Checker24Hours.mp4)).

Also, you may search for these keywords: `control flow graph`, `control flow graph analysis`, and so on.

P.S. please, let me know if you find something valuable ;)

**Comment by luohs** [comment]
Hi! @AlexDenisov

How to set OTHER_CFLAGS with target of xcodeproject that used with pods？Thank you！
