### ISSUE TITLE
How to set OTHER_CFLAGS used with Pods

### ISSUE THREAD

**Issue by luohs** [AlexDenisov/ToyClangPlugin#3]
Hi! @AlexDenisov

How to set OTHER_CFLAGS with target of xcodeproject that used with pods？Thank you！

**Comment by AlexDenisov** [comment]
I'm not sure if I get it right. Could you elaborate please?

**Comment by luohs** [comment]
My project manage third libraries with CocoaPods, when I set the OTHER_CFLAGS settings, the plugin can't analyse third libraries files。
![1](https://user-images.githubusercontent.com/4815712/26858243-ad10fe66-4b62-11e7-9f60-ce52e0668a49.png)
![2](https://user-images.githubusercontent.com/4815712/26858244-ad573160-4b62-11e7-9c19-895f088ba731.png)

Thank you!
